### ISSUE TITLE
The extension does not change the JSON config, log seems to be ok

### ISSUE THREAD

**Issue by alex-netkachov** [hegsie/Wix4JsonFileExtension#1]
Hi!

I've added the JsonFile directive to the project, and it seems that it is replaced, however the installed file is unchanged. Some details:

I've added `DeployAppSettings` attribute by transforming harvested results. In obj's `_AppComponents_dir.wxs`:

```
        <DirectoryRef Id="INSTALLFOLDER">
            <Component Id="cmpN1YDbNWtqH.nEoZvn.aEtfLXHi8" Guid="*">
                <File Id="DeployAppSettings" KeyPath="yes" Source="$(var.AppPublishDir)\appSettings.json" />
            </Component>
```

added a few instructions to Product:

```
    <ComponentGroup Id="ConfigComponentGroup" Directory="INSTALLFOLDER">
      <Component Id="ConfigComponent" Guid="7732c259-55ad-45dc-89f1-81c6c6906f4f">
        <Json:JsonFile Id="test1" File="[#DeployAppSettings]" ElementPath="$.test1" Action="deleteValue" />
        <Json:JsonFile Id="test2" File="[#DeployAppSettings]" ElementPath="$.test2" Value="1" />
```

the appSettings.json in project's folder:

```
{
  "test1": 0,
  "test2": 0,
  "System": {
```

According to the log, the values are processed:

```
Wix4JsonFile:  Entered Wix4JsonFile CA
Wix4JsonFile:  Created PMSIHANDLE hView
Wix4JsonFile:  Created PMSIHANDLE hRec
Wix4JsonFile:  MSIHANDLE's created for Wix4JsonFile CA
Wix4JsonFile:  Getting Wix4JsonFile Id.
Wix4JsonFile:  Getting Wix4JsonFile File for Id:test1
Wix4JsonFile:  Getting Wix4JsonFile ElementPath for Id:test1
Wix4JsonFile:  Getting Wix4JsonFile Value for Id:test1
Wix4JsonFile:  Getting Wix4JsonFile Flags for Id:test1
Wix4JsonFile:  Getting Wix4JsonFile Component for Id:test1
Wix4JsonFile:  Updating Wix4JsonFile for Id:test1
Wix4JsonFile:  Created wifstream, C:\Program Files\MyApp\appSettings.json
Wix4JsonFile:  Using the following flags, 1, false
Wix4JsonFile:  Found ElementPath as $.test1
Wix4JsonFile:  Updated ElementPath [ to $.test1
Wix4JsonFile:  Updated ElementPath ] to $.test1
Wix4JsonFile:  Found create set to false
Wix4JsonFile:  About to delete value: |$.test1| with value(s) Wix4JsonFile:  About to delete value: |$.test1| with value(s) [0]  
Wix4JsonFile:  Deleted the json $.test1
Wix4JsonFile:  created output stream
Wix4JsonFile:  dumped output stream
Wix4JsonFile:  closed output stream
Wix4JsonFile:  Getting Wix4JsonFile Id.
Wix4JsonFile:  Getting Wix4JsonFile File for Id:test2
Wix4JsonFile:  Getting Wix4JsonFile ElementPath for Id:test2
Wix4JsonFile:  Getting Wix4JsonFile Value for Id:test2
Wix4JsonFile:  Getting Wix4JsonFile Flags for Id:test2
Wix4JsonFile:  Getting Wix4JsonFile Component for Id:test2
Wix4JsonFile:  Updating Wix4JsonFile for Id:test2
Wix4JsonFile:  Created wifstream, C:\Program Files\MyApp\appSettings.json
Wix4JsonFile:  Using the following flags, 2, true
Wix4JsonFile:  Found ElementPath as $.test2
Wix4JsonFile:  Updated ElementPath [ to $.test2
Wix4JsonFile:  Updated ElementPath ] to $.test2
Wix4JsonFile:  Found create set to false
Wix4JsonFile:  Found 1 elements
Wix4JsonFile:  About to replace value: |$.test2| {1}
Wix4JsonFile:  Updating the json $.test2 with values 1.
Wix4JsonFile:  created output stream
Wix4JsonFile:  dumped output stream
Wix4JsonFile:  closed output stream
Wix4JsonFile:  Closed PMSIHANDLE hView
Action ended 16:05:08: Wix4JsonFile_X64. Return value 1.
Action ended 16:05:08: INSTALL. Return value 1.
Property(S): ALLUSERS = 1
```

However, after the installation, the file `C:\Program Files\MyApp\appSettings.json` is not modified  (it has both test1 and test2, set to 0).

Any ideas what is wrong?

Update:

I found that the replacement is working, but only when the current user is a read admin, i.e. the following MSI properties are set:

```
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
```

Assuming that there is a PS1 file that runs the installer, e.g. `Install.ps1`:

```
path_to_msi\Installer.msi /L*v Install.log
```

These steps result with modified JSON file:

1. Open the Windows Terminal with PowerShell as Administrator.
2. Run Install.ps1

These steps result with unmodified JSON file:

1. Open the Windows Terminal with PowerShell
2. Run Install.ps1
3. Click  Yes in UAC prompt (current user is in Adminstrator's group)

**Comment by benhegartysefe** [comment]
what version of the nuget package are you using? can you share the nuget link?

**Comment by alex-netkachov** [comment]
In the installed I have the following references:

```
  <ItemGroup>
      <PackageReference Include="Wix4JsonFileExtension" Version="4.0.0.16" />
      <PackageReference Include="WixToolset.Heat" Version="4.0.3" />
  </ItemGroup>
```

These are latest versions of these packages.

Also I found when Wix4JsonFileExtension does work: if the installer is called from terminal opened as Administrator, JSON file is updated in the installed folder. When the installer starts under the current user and opens UAC prompt, JSON file is not updated. Could it be that the Wix4JsonFileExtension's action is started under the user who called the installer and does not inherit admin's permissions?

**Comment by hegsie** [comment]
Can you try this with the latest package now and see if it errors out when privs are missing?

**Comment by alex-netkachov** [comment]
The last fix is not helping, unfortunately.

I think this may help:

<img width="803" alt="image" src="https://github.com/hegsie/Wix4JsonFileExtension/assets/914986/b9626508-7a7d-45c3-a07f-a8272c6c6693">

I've tried to test the fix, be the project does not build with an error:

> The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/

**Comment by hegsie** [comment]
Hi,

Yer I noticed that after I released it, there is a new version that sorts it, please try again

Regards
Ben

**Comment by alex-netkachov** [comment]
I've tested with 4.0.0.19. It is a latest available at the Nuget at the moment.

**Comment by hegsie** [comment]
Can you test with the latest version and confirm if it fixes the issue?
