### ISSUE TITLE
 The identifier 'CustomAction:Wix4SchedJsonFile_X86' could n ot be found.

### ISSUE THREAD

**Issue by Temeos** [hegsie/Wix4JsonFileExtension#2]
I get the above error for the following code: 

```
<DirectoryRef Id="INSTALLFOLDER">

	<Component Id="WebConfigCmp" Guid="GUID here">
		<File Id="WebConfigFile" KeyPath="yes"
		  Source="$(var.publishDir)\appsettings.Development.json" Vital="yes" />
		<Json:JsonFile
				 Id="setAppSettings"
				 ElementPath="$.ConnectionStrings[\[]0[\]].ConnString"
				 File="[#WebConfigFile]"
				 Value="[CONNECTION_STRING]"
				 Action="setValue"/>
	</Component>
</DirectoryRef>
``` 

I am building the package via developer console with msbuild. the command i am executing in the build script is:

`wix build -ext WixToolset.Iis.wixext -ext C:\Users\PLJ\.nuget\packages\wix4jsonfileextension\4.0.0.25\wixext4\Wix4JsonFileExtension.dll -ext WixToolset.Util.wixext -ext WixToolset.UI.wixext -d publishDir=$(Publish) -d Version=$(PackageVersion) -d ProductCode=$(ProductCode) -d MyWebResourceDir=. -o $(MsiOut) @(WixCode, &apos; &apos;)`

This is the full error: 
```
error WIX0094: The identifier 'CustomAction:Wix4SchedJsonFile_X86' could not be found. 
Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker. 
```

**Comment by benhegartysefe** [comment]
I haven't actually built a win32 version, on win64, change your Msi over and it should work around this problem.

**Comment by Temeos** [comment]
Thank you for the quick answer!
